# Linguagem Utilizada para Desenvolver a Aplicação
language: php

# Versão que a aplicação suporta.
php:
  - "7.2"
phpunit:
  - "7"

sudo: required

install:
  - composer install
  - php bin/console assets:install
  - php bin/console cache:clear
  - php bin/console cache:warmup
  - sudo chmod 777 -R var/cache var/logs var/sessions

before_script:
  - curl -sSfL -o phpunit https://phar.phpunit.de/phpunit-7.phar
  
script:
  - php phpunit src/AppBundle/Tests

#deploy:
  #provider: heroku
  #api-key: 
    #secure: $HEROKU_API_KEY
  #app: mybillshub