# Linguagem Utilizada para Desenvolver a Aplicação
language: php

# Versão que a aplicação suporta.
php:
  - "7.2"
phpunit:
  - "7"

sudo: required

install:
  - composer install
  - php bin/console assets:install

before_script:
  - curl -sSfL -o phpunit https://phar.phpunit.de/phpunit-7.phar
  
script:
  - php phpunit symfony

# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
#deploy:
#  provider: heroku
#  api-key: 
#    secure: $HEROKU_API_KEY
#  app: devopslabs-helloworld