# Linguagem Utilizada para Desenvolver a Aplicação
language: php

# Versão que a aplicação suporta.
python:
  - "7.2"

# Faz a instalação com Sudo, para ter privilégio de Super Usuário.
sudo: required

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - composer install
  - php bin/console assets:install

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - php ./phpunit symfony

# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
#deploy:
#  provider: heroku
#  api-key: 
#    secure: $HEROKU_API_KEY
#  app: devopslabs-helloworld