app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"