# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.search:
        class: AppBundle\Service\SearchService
        arguments: ['@doctrine.orm.entity_manager', '@security.authorization_checker']

    app.recurrence_payment:
        class: AppBundle\Service\RecurrencePaymentService
        arguments: ['@doctrine.orm.entity_manager']